version: '3'
services:
  app:
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    container_name: eat
    image: eat-app
    build: .
    ports:
      - "8080:8080"
  postgres:
    container_name: postgres
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - ./sql/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.0.7
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8181:8080"
    command: start-dev