truncate table eat.databasechangelog;
drop table if exists eat.event_template cascade;
drop sequence if exists eat.event_template_seq;
drop table if exists eat.event cascade;
drop sequence if exists eat.event_seq;
drop table if exists eat.loot cascade;
drop sequence if exists eat.loot_seq;
drop table if exists eat.mtm_event_loot cascade;
drop sequence if exists eat.mtm_event_loot_seq;
drop table if exists eat.guild_member cascade;
drop sequence if exists eat.guild_member_seq;